import { HelpCircle, Mail, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Accordion, AccordionContent, AccordionItem, AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    q: "How does the AI Life Score work?",
    a: "Your Life Score is calculated using your lifestyle inputs—sleep, hydration, exercise, nutrition and stress levels. The AI analyzes trends over time and provides a holistic score from 0 to 100.",
  },
  {
    q: "How are my lifestyle insights generated?",
    a: "Insights are generated by our AI coach, which analyzes your daily habits and compares them against evidence-based health recommendations to give you personalized tips.",
  },
  {
    q: "How can I improve my health score?",
    a: "Focus on consistent sleep, regular hydration, daily movement, and balanced nutrition. The AI coach will provide specific suggestions tailored to your data.",
  },
];

export default function HelpSupport() {
  return (
    <div className="grid gap-4">
      <div className="flex items-center gap-2 mb-2">
        <HelpCircle size={20} className="text-primary" />
        <h2 className="text-lg font-display font-bold">Help & Support</h2>
      </div>

      <div className="glass-card p-4">
        <p className="text-sm text-muted-foreground leading-relaxed mb-4">
          If you need help using <span className="text-foreground font-medium">AI Life Copilot</span>, contact us.
        </p>
        <p className="text-sm mb-4">
          <Mail size={14} className="inline mr-1.5 text-muted-foreground" />
          <a href="mailto:support@ailifecopilot.app" className="text-primary hover:underline">
            support@ailifecopilot.app
          </a>
        </p>
        <div className="flex gap-2">
          <Button size="sm" asChild>
            <a href="mailto:support@ailifecopilot.app">
              <Mail size={14} className="mr-1.5" /> Send Email
            </a>
          </Button>
          <Button size="sm" variant="outline" asChild>
            <a href="https://ailifecopilot.app/help" target="_blank" rel="noopener noreferrer">
              <ExternalLink size={14} className="mr-1.5" /> Help Center
            </a>
          </Button>
        </div>
      </div>

      <div className="glass-card p-4">
        <p className="font-medium text-sm mb-3">Frequently Asked Questions</p>
        <Accordion type="single" collapsible className="w-full">
          {faqs.map((faq, i) => (
            <AccordionItem key={i} value={`faq-${i}`} className="border-border/50">
              <AccordionTrigger className="text-sm text-left hover:no-underline py-3">
                {faq.q}
              </AccordionTrigger>
              <AccordionContent className="text-sm text-muted-foreground">
                {faq.a}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </div>
  );
}
